title: "King Napoleon of Rhodesia"
description: "A site dedicated to Napoleon I, the King of Rhodesia, who rules through dance moves and tater tots."
author: "King of Rhodesia"
baseurl: ""
url: "https://kingofrhodesia.gitub.io"
markdown: kramdown
theme: null
